### ISSUE TITLE
The icons just doesn't show for me.

### ISSUE THREAD

**Issue by shubhampant13** [ihodev/a-file-icon#162]
I have followed every single step and guidance, but it just doesn't work. (using Linux)
Spent an hour on this and restarting sublime text almost 100 times but it just doesn't work.
I can't say its a bug, but i just don't see the icons. Is it so tough. 
Can somebody help plz. Mail : shubhampant13@gmail.com

#### Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by ethaligan** [comment]
I'm currently facing the same issue.
Reinstalled Sublime a few times, icons are still not appearing.

Using default settings on Windows 10 (1803).

**Comment by mallowigi** [comment]
The developer doesn't work on his plugin anymore.

**Comment by ihodev** [comment]
> I have followed every single step and guidance, but it just doesn't work.
> I'm currently facing the same issue.
@ethaligan @shubhampant13 Please provide ST's console output.

> The developer doesn't work on his plugin anymore.
That's partially correct. I have huge lack of free time, but I hope this will change in the near future.

**Comment by ethaligan** [comment]
Hey @ihodev, thanks for your fast reply.

Here's the bad guy
```python
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1007, in run_
    return self.run()
  File "C:\Users\Adrien\AppData\Roaming\Sublime Text 3\Installed Packages\A File Icon.sublime-package\core/themes.py", line 214, in run
  File "C:\Users\Adrien\AppData\Roaming\Sublime Text 3\Installed Packages\A File Icon.sublime-package\common/utils/icons.py", line 25, in get_missing
  File "C:\Users\Adrien\AppData\Roaming\Sublime Text 3\Installed Packages\A File Icon.sublime-package\common/utils/icons.py", line 25, in <listcomp>
TypeError: startswith first arg must be str or a tuple of str, not bool
```

**Comment by ihodev** [comment]
> After some tests, the exception only occurs in conjunction with DA UI theme (on my side).
Am I right, you are able to see this exception only with `DA UI` or with `Ayu`, `Material Theme` and `Boxy` themes?

**Comment by ethaligan** [comment]
I tried all the themes you specified and the icons are visible on all of them, except on DA UI.

By the way, I have another computer, running the same Windows and Sublime versions, and your module is working fine with DA UI. 😕

**Comment by ihodev** [comment]
@ethaligan That's very strange and I'll be back when I have some news for you 😞

**Comment by ethaligan** [comment]
Thanks @ihodev 😃 

I'll try on my side too, if I have any news, I'll let you know.

**Comment by ethaligan** [comment]
Hey @ihodev,
I digged a little further on this issue 😄 

**DA Theme.sublime-settings**
```json
{
    "show_sidebar_file_icons": false
}
```

Setting this option to false shows the icons, but folder icons are still missing.
Is **DA UI** _overriding_ **A File Icon** icons?

I begin to think that the problem is coming from **DA UI** itself and not from this package since other themes are working fine. 😕

**Comment by ihodev** [comment]
Oh My Lord! @ethaligan, you're a tough guy ;) Thanks! I remembered the stuff that can cause this bug

> Is DA UI overriding A File Icon icons

Partially, yes. It doesn't override, but it can introduce the settings that the current version of `A File Icon` doesn't like, that's why I've decided before to re-implement `A File Icon` first, before the next `DA UI` release.

> I begin to think that the problem is coming from DA UI itself and not from this package since other themes are working fine. 

The problem is in your **DA UI – User** settings, `A File Icon` doesn't like something. It would be great if you provide here [this output](https://github.com/ihodev/sublime-da-ui#found-an-issue).

> I begin to think that the problem is coming from DA UI itself and not from this package since other themes are working fine. 

@shubhampant13 Are you facing the same issue or in your case icons aren't visible with any theme?

**Comment by ihodev** [comment]
OK, I reproduced the issue. It happens in combination of `A File Icon` & `DA UI`, will fix with next release. However I don't have any ETA, too busy at work.

**Comment by shubhampant13** [comment]
Dear, when i open individual files, it doesn't show me the icons for those file, but when i open an entire folder containing multiple files, then the icons are visible. Is this extension designed to work this way, i.e. when we open an entire folder, then only the icons would be visible for the files.

**Comment by Smurfz87** [comment]
@shubhampant13 apparently the way it is intended, and is not intended implemented for files in the "Open Files" section. Ref. issues #131 and (sublime text issues) [#1595](https://github.com/SublimeTextIssues/Core/issues/1595)
