### ISSUE TITLE
Icons disappeared after recent plugin update

### ISSUE THREAD

**Issue by TravelingTechGuy** [ihodev/a-file-icon#87]
### Expected behavior
Would like to see file icons :)

#### Current Behavior
Just opened ST. Got message about plugin being updated from 'zz File Icon' to 'A File Icon'.
All icons (with exception of folder icon) disappered. Tried all of the above troubleshooting steps, and got nothing. Still no icons. 

Removed the plugin, and got the ST default icons. Re-installed the plugin, and no icons.

#### Your Environment
<b>Platform:</b> Windows 10<br>
<b>A File Icon:</b> 3.0.0<br>
<b>Sublime Text:</b> 3125<br>
<b>Package Control:</b> True<br>
<b>Current Theme:</b> Default.sublime-theme<br>
<b>Installed Themes:</b><br>
<ul>
  <li>Oceanic Next Color Scheme</li>
  <li>Theme - Default</li>
</ul>

**Comment by ihodev** [comment]
Please provide also your console output with "dev_mode": true. Also did you try all steps from issue template?

**Comment by TravelingTechGuy** [comment]
As you can see in my original post, I tried all the steps suggested, and even re-installed - to no avail.
Here's my console dump:

```
DPI scale: 1.5
startup, version: 3125 windows x64 channel: dev
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.121762
startup time: 0.168762
first paint time: 0.183762
first paint time: 0.183762
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin DocBlockr.jsdocs
reloading plugin EditorConfig.EditorConfig
reloading plugin FileDiffs.file_diffs
reloading plugin HexViewer.hex_checksum
Hex Viewer: md2 hash is not available!
reloading plugin HexViewer.hex_common
reloading plugin HexViewer.hex_editor
reloading plugin HexViewer.hex_finder
reloading plugin HexViewer.hex_highlighter
reloading plugin HexViewer.hex_inspector
reloading plugin HexViewer.hex_notify
reloading plugin HexViewer.hex_viewer
reloading plugin HexViewer.hex_writer
reloading plugin HexViewer.sum_hashes
reloading plugin HexViewer.support
reloading plugin HexViewer.tiger
reloading plugin HexViewer.whirlpool
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeGit.SublimeGit
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
reloading plugin TodoReview.TodoReview
plugins loaded
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "A File Icon in C:\Users\Guy\AppData\Roaming\Sublime Text 3\Installed Packages\A File Icon.sublime-package", line 20, in plugin_loaded
  File "common.settings in C:\Users\Guy\AppData\Roaming\Sublime Text 3\Installed Packages\A File Icon.sublime-package", line 261, in init
  File "common.settings in C:\Users\Guy\AppData\Roaming\Sublime Text 3\Installed Packages\A File Icon.sublime-package", line 199, in sublinter
KeyError: 'syntax_map'
SublimeLinter: debug mode: off 
Package Control: Skipping automatic upgrade, last run at 2017-02-10 09:24:42, next run at 2017-02-10 10:24:42 or after
loading dictionary Packages/Language - English/en_US.dic
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\Guy\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Guy\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\Guy\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\Guy\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\Guy\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 962, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "C:\Users\Guy\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 137, in highlight
    vid = view.id()
AttributeError: 'NoneType' object has no attribute 'id'
 
SublimeLinter: -------------------- 
```

**Comment by ihodev** [comment]
Ok, it seems like you have some problems (typo or something else) in SublimeLinter settings. Plugin updates them automatically after each upgrade to add missing aliases. I'll fix exception handling and release 3.0.1 today.

**Comment by ihodev** [comment]
@TravelingTechGuy , 3.0.1 should fix your problem. However can you provide your SublimeLinter settings?

1. Open your packages folder using menu item `Preferences → Browse Packages...`
2. Provide contents of the next files:
    - `Packages/SublimeLinter/SublimeLinter.sublime-settings`
    - `Packages/User/SublimeLinter.sublime-settings`     

Thanks a lot for reporting this issue 😉

**Comment by TravelingTechGuy** [comment]
My pleasure 😉

Packages/SublimeLinter/SublimeLinter.sublime-settings:

```
{
    "default": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "python django": "python",
            "pythonimproved": "python",
            "magicpython": "python",
            "html 5": "html",
            "html (django)": "html",
            "html (rails)": "html",
            "javascript (babel)": "javascript",
            "php": "html"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

Packages/User/SublimeLinter.sublime-settings:

```
{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "eslint": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```
